Update cmake.yml

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -35,17 +35,17 @@ jobs:
       run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
 
     - name: Unit Tests
-      working-directory: ${{github.workspace}}/build
+      working-directory: ${{github.workspace}}/build/test
       # Execute unit tests.
       run: AdventOfCode2022Tests --log_format=JUNIT --log_level=all --log_sink=report.xml
 
     - name: Test Report
       uses: dorny/test-reporter@v1
-      if: success() || failure()    # run this step even if previous step failed
+      if: success() || failure()                                     # run this step even if previous step failed
       with:
-        name: Unit Tests            # Name of the check run which will be created
-        path: report.xml            # Path to test results
-        reporter: jest-junit        # Format of test results
+        name: Unit Tests                                             # Name of the check run which will be created
+        path: ${{github.workspace}}/build/test/report.xml            # Path to test results
+        reporter: jest-junit                                         # Format of test results
           
     - name: Integration Tests
       working-directory: ${{github.workspace}}/build
