Update cmake.yml

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -44,17 +44,16 @@ jobs:
       run: ./AdventOfCode2022Tests --log_format=JUNIT --log_level=all --log_sink=report.xml
 
     - name: Test Report
-      uses: dorny/test-reporter@v1
+      uses: mikepenz/action-junit-report@v3
       if: success() || failure()                                     # run this step even if previous step failed
       with:
-        name: Unit Tests                                             # Name of the check run which will be created
-        path: ${{github.workspace}}/build/test/report.xml            # Path to test results
-        reporter: jest-junit                                         # Format of test results
+        report_paths: ${{github.workspace}}/build/test/report.xml    # Path to test results
           
     - name: Run Integration Tests
       working-directory: ${{github.workspace}}/build
       # Execute tests defined by the CMake configuration.
       # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
+      if: success() || failure()                                     # run this step even if previous step failed
       run: ctest -C ${{env.BUILD_TYPE}}
       
     - name: Install
