Update cmake.yml
Add unit tests execution and reporting

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -37,8 +37,16 @@ jobs:
     - name: Unit Tests
       working-directory: ${{github.workspace}}/build
       # Execute unit tests.
-      run: AdventOfCodeTests
+      run: AdventOfCode2022Tests --log_format=JUNIT --log_level=all --log_sink=report.xml
 
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Unit Tests            # Name of the check run which will be created
+        path: report.xml            # Path to test results
+        reporter: jest-junit        # Format of test results
+          
     - name: Integration Tests
       working-directory: ${{github.workspace}}/build
       # Execute tests defined by the CMake configuration.
